#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Yuno OS Portage Configuration Module for Calamares
#

import os
import subprocess
import multiprocessing
import libcalamares

# CFLAGS presets
CFLAGS_PRESETS = {
    "safe": "-march=x86-64 -O2 -pipe",
    "optimized": "-march=native -O2 -pipe",
    "aggressive": "-march=native -O3 -pipe -flto=auto",
}

def get_cpu_count():
    """Get the number of CPU cores."""
    return multiprocessing.cpu_count()

def generate_make_conf(root_mount_point):
    """Generate make.conf based on user selections."""
    gs = libcalamares.globalstorage

    # Get user selections
    cflags_preset = gs.value("cflagsPreset") or "optimized"
    custom_cflags = gs.value("customCflags") or ""
    use_flags = gs.value("useFlags") or []
    video_cards = gs.value("videoCards") or ""
    binary_pref = gs.value("binaryPreference") or "prefer"
    init_system = gs.value("initSystem") or "openrc"

    # Determine CFLAGS
    if cflags_preset == "custom" and custom_cflags:
        cflags = custom_cflags
    else:
        cflags = CFLAGS_PRESETS.get(cflags_preset, CFLAGS_PRESETS["optimized"])

    # Build make.conf content
    cpu_count = get_cpu_count()
    makeopts = f"-j{cpu_count}"

    content = f"""# Yuno OS make.conf - Generated by installer
# See /usr/share/portage/config/make.conf.example for reference

# Compiler flags
COMMON_FLAGS="{cflags}"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"
RUSTFLAGS="-C target-cpu=native"

# Build parallelism
MAKEOPTS="{makeopts}"
EMERGE_DEFAULT_OPTS="--jobs={cpu_count // 2 + 1} --load-average={cpu_count}"

"""

    # USE flags
    if use_flags:
        content += f'# Global USE flags\nUSE="{" ".join(use_flags)}"\n\n'

    # VIDEO_CARDS
    if video_cards:
        content += f'# Graphics drivers\nVIDEO_CARDS="{video_cards}"\n\n'

    # Input devices
    content += '# Input devices\nINPUT_DEVICES="libinput"\n\n'

    # Accept license
    content += '# Accept all licenses\nACCEPT_LICENSE="*"\n\n'

    # Features
    features = ["parallel-fetch", "candy", "buildpkg"]
    if binary_pref in ["prefer", "only"]:
        features.append("getbinpkg")

    content += f'# Portage features\nFEATURES="{" ".join(features)}"\n\n'

    # Grub platforms
    content += '# Bootloader\nGRUB_PLATFORMS="efi-64"\n\n'

    # Write make.conf
    make_conf_path = os.path.join(root_mount_point, "etc/portage/make.conf")
    os.makedirs(os.path.dirname(make_conf_path), exist_ok=True)

    with open(make_conf_path, 'w') as f:
        f.write(content)

    return True

def setup_repos_conf(root_mount_point):
    """Setup repos.conf directory."""
    repos_dir = os.path.join(root_mount_point, "etc/portage/repos.conf")
    os.makedirs(repos_dir, exist_ok=True)

    gentoo_conf = """[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = rsync
sync-uri = rsync://rsync.gentoo.org/gentoo-portage
auto-sync = yes
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
"""

    conf_path = os.path.join(repos_dir, "gentoo.conf")
    with open(conf_path, 'w') as f:
        f.write(gentoo_conf)

    return True

def setup_package_use(root_mount_point):
    """Setup package.use directory."""
    use_dir = os.path.join(root_mount_point, "etc/portage/package.use")
    os.makedirs(use_dir, exist_ok=True)

    gs = libcalamares.globalstorage
    desktop = gs.value("desktopType") or ""
    gpu_driver = gs.value("gpuDriver") or ""

    content = "# Yuno OS package-specific USE flags\n"

    # Desktop-specific flags
    if "kde" in desktop.lower() or "plasma" in desktop.lower():
        content += "\n# KDE Plasma\nkde-plasma/* wayland\nkde-apps/* wayland\n"
    elif "gnome" in desktop.lower():
        content += "\n# GNOME\ngnome-base/* wayland\n"

    # GPU-specific flags
    if "nvidia" in gpu_driver.lower():
        content += "\n# NVIDIA\nx11-drivers/nvidia-drivers modules\n"

    use_path = os.path.join(use_dir, "yuno")
    with open(use_path, 'w') as f:
        f.write(content)

    return True

def sync_portage(root_mount_point):
    """Sync the Portage tree."""
    libcalamares.utils.debug("Syncing Portage tree")

    try:
        subprocess.run([
            "chroot", root_mount_point,
            "emerge-webrsync"
        ], check=True, timeout=600)
        return True
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(f"Portage sync failed: {e}")
        return False
    except subprocess.TimeoutExpired:
        libcalamares.utils.warning("Portage sync timed out")
        return False

def select_profile(root_mount_point):
    """Select the appropriate Gentoo profile."""
    gs = libcalamares.globalstorage

    init_system = gs.value("initSystem") or "openrc"
    desktop = gs.value("desktopType") or ""

    # Determine profile
    profile = "default/linux/amd64/23.0"

    if desktop:
        profile += "/desktop"
        if "kde" in desktop.lower() or "plasma" in desktop.lower():
            profile += "/plasma"
        elif "gnome" in desktop.lower():
            profile += "/gnome"

    if init_system == "systemd":
        profile += "/systemd"

    libcalamares.utils.debug(f"Selecting profile: {profile}")

    try:
        subprocess.run([
            "chroot", root_mount_point,
            "eselect", "profile", "set", profile
        ], check=True)
        return True
    except subprocess.CalledProcessError:
        # Try without desktop-specific suffix
        try:
            base_profile = "default/linux/amd64/23.0/desktop"
            if init_system == "systemd":
                base_profile += "/systemd"
            subprocess.run([
                "chroot", root_mount_point,
                "eselect", "profile", "set", base_profile
            ], check=True)
            return True
        except subprocess.CalledProcessError as e:
            libcalamares.utils.warning(f"Profile selection failed: {e}")
            return False

def run():
    """Main entry point for the module."""
    root_mount_point = libcalamares.globalstorage.value("rootMountPoint")

    if not root_mount_point:
        return ("No root mount point", "Root mount point not found in global storage")

    # Generate make.conf
    libcalamares.job.setprogress(0.1)
    if not generate_make_conf(root_mount_point):
        return ("make.conf Error", "Failed to generate make.conf")

    # Setup repos.conf
    libcalamares.job.setprogress(0.2)
    if not setup_repos_conf(root_mount_point):
        return ("repos.conf Error", "Failed to setup repos.conf")

    # Setup package.use
    libcalamares.job.setprogress(0.3)
    if not setup_package_use(root_mount_point):
        return ("package.use Error", "Failed to setup package.use")

    # Sync Portage
    libcalamares.job.setprogress(0.4)
    if not sync_portage(root_mount_point):
        return ("Portage Sync Error", "Failed to sync Portage tree")

    # Select profile
    libcalamares.job.setprogress(0.9)
    if not select_profile(root_mount_point):
        libcalamares.utils.warning("Profile selection failed, continuing anyway")

    libcalamares.job.setprogress(1.0)
    return None
